name: Check Action Metadata

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-action-metadata-task.ya?ml"
      - ".npmrc"
      - "action.ya?ml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "Taskfile.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/check-action-metadata-task.ya?ml"
      - ".npmrc"
      - "action.ya?ml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "Taskfile.ya?ml"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage from changes to the JSON schema.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install Task
        uses: go-task/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Validate action.yml
        run: task --silent action:validate
